name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: compile n package docker image
      run: mvn -B spring-boot:build-image
    - name: docker images
      run: docker images
    - name: docker images scan
      uses: azure/container-scan@v0
      with:
        image-name: springboot-reactive:0.0.1-SNAPSHOT
